package ppak.cret.weather;

import javafx.scene.image.Image;

/**
 * Interface marking all of weather types generated by WeatherFactory
 * @see WeatherFactory
 * @see ppak.cret.weather.types.WeatherType
 */
public interface Weather {
    /**
     * Gets temperature stored in Weather object
     * @return temperature value
     */
    double getTemperature();
    /**
     * Gets pressure value stored in Weather object
     * @return pressure value
     */
    double getPressure();
    /**
     * Gets humidity value stored in Weather object
     * @return humidity value
     */
    double getHumidity();
    /**
     * Gets cloud coverage (percentage) value stored in Weather object
     * @return cloud coverage value
     */
    double getClouds();
    /**
     * Gets image representing weather type
     * @return weather type icon
     */
    Image getWeatherIcon();
    /**
     * Gets overall description of current weather
     * @return description of current weather
     */
    String getDescription();
    /**
     * Gets currently set location
     * @return city name, comma, country
     */
    String getLocation();
}
